module.exports = [
	{
		title: "1917",
		description:
			"1917 is a 2019 British war film directed and produced by Sam Mendes, who co-wrote the film with Krysty Wilson-Cairns.",
		year: "2019",
		director: "Sam Mendes",
		cast: "Dean-Charles",
		runtime: "119 minutes",
		language: "English",
		rating: "8.3 Imdb",
		season: null,
		genre: "Action,Drama,War",
		certification: "U",
	},
	{
		title: "The Irishman",
		description:
			"The Irishman (titled onscreen as I Heard You Paint Houses) is a 2019 American epic crime drama film directed and produced by Martin Scorsese and written by Steven Zaillian, based on the 2004 nonfiction book I Heard You Paint Houses by Charles Brandt. ",
		year: "2019",
		director: "Martin Scorsese",
		cast: "Robert De Niro",
		runtime: "209 minutes",
		language: "English",
		rating: "7.8 Imdb",
		season: null,
		genre: "Crime,Biography,Drama",
		certification: "U",
	},
	{
		title: "Avatar",
		description:
			"Avatar (also marketed as James Cameron's Avatar) is a 2009 American epic science fiction film directed, written, produced, and co-edited by James Cameron.",
		year: "2009",
		director: "James Cameron",
		cast: "Sam Worthington",
		runtime: "162 minutes",
		language: "English",
		rating: "7.8 Imdb",
		season: null,
		genre: "Action,Adventure,Fantasy",
		certification: "U",
	},
	{
		title: "The Godfather",
		description:
			"The Godfather is a 1972 American crime film directed by Francis Ford Coppola, who co-wrote the screenplay with Mario Puzo, based on Puzo's best-selling 1969 novel of the same name.",
		year: "1972",
		director: "Francis Ford",
		cast: "Al Pacino",
		runtime: "177 minutes",
		language: "English",
		rating: "9.2 Imdb",
		season: null,
		genre: "Crime,Drama",
		certification: "UA",
	},
	{
		title: "The Imitation Game",
		description:
			"During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians while attempting to come to terms with his trouble..",
		year: "2014",
		director: "Morten Tyldum",
		cast: "Benedict Cumberbatch",
		runtime: "114 minutes",
		language: "English",
		rating: "8.0 Imdb",
		season: null,
		genre: "Biography,Drama,Thriller",
		certification: "U",
	},
	{
		title: "Mad Max 2",
		description:
			"In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named ...",
		year: "1979",
		director: "George Miller",
		cast: "Tom Hardy",
		runtime: "120 minutes",
		language: "English",
		rating: "8.1 Imdb",
		season: null,
		genre: "Action,Adventure,Sci-fi",
		certification: "UA",
	},
	{
		title: "Johnny English",
		description:
			"After a sudden attack on MI5, Johnny English, Britain's most confident, yet unintelligent spy, becomes Britain's only spy.",
		year: "2003",
		director: "Peter Howitt",
		cast: "Rowan Atkinson",
		runtime: "98 minutes",
		language: "English",
		rating: "7.0 Imdb",
		season: null,
		genre: "Action,Adventure,Comedy",
		certification: "U",
	},
	{
		title: "The Shawshank Redemption",
		description:
			"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
		year: "1994",
		director: "Frank Darabont",
		cast: "Tim Robbins",
		runtime: "150 minutes",
		language: "English",
		rating: "9.3 Imdb",
		season: null,
		genre: "Drama",
		certification: "UA",
	},
	{
		title: "Peacemaker",
		description:
			"Picking up where The Suicide Squad (2021) left off, Peacemaker returns home after recovering from his encounter with Bloodsport - only to discover that his freedom comes at a price.",
		year: "2022",
		director: "James Gunn",
		cast: "John Cena",
		runtime: "40 minutes",
		language: "English",
		rating: "8.5 Imdb",
		season: null,
		genre: "TV Series",
		certification: "U",
	},
	{
		title: "Cherry",
		description:
			"Cherry drifts from college dropout to army medic in Iraq - anchored only by his true love, Emily. But after returning from the war with PTSD, his life spirals into drugs and crime as he stru..",
		year: "2021",
		director: "Anthony Russo",
		cast: "Tom Holland",
		runtime: "143 minutes",
		language: "English",
		rating: "6.7 Imdb",
		season: null,
		genre: "Crime,Drama",
		certification: "UA",
	},
	{
		title: "It",
		description:
			"In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town...",
		year: "2017",
		director: "A Muschietti",
		cast: "Bill Skarsgard",
		runtime: "135 minutes",
		language: "English",
		rating: "7.3 Imdb",
		season: null,
		genre: "Horror",
		certification: "U",
	},
	{
		title: "The Dark Knight Rises",
		description:
			"Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane",
		year: "2012",
		director: "C Nolan",
		cast: "Chriatian Bale",
		runtime: "165 minutes",
		language: "English",
		rating: "8.4 Imdb",
		season: null,
		genre: "Action,Crime,Drama",
		certification: "UA",
	},
	{
		title: "Wolverine",
		description:
			"Wolverine comes to Japan to meet an old friend whose life he saved years ago, and gets embroiled in a conspiracy involving yakuza and mutants.",
		year: "2013",
		director: "James Mangold",
		cast: "Hugh Jackman",
		runtime: "126 minutes",
		language: "English",
		rating: "6.7 Imdb",
		season: null,
		genre: "Action,Sci-fi",
		certification: "A",
	},
	{
		title: "F2:Hobbs & Shaw",
		description:
			"Alex Zane meets the cast on the set of Fast and Furious - Hobbs and Shaw.",
		year: "2019",
		director: "David Leitch",
		cast: "Dwayne Johnson",
		runtime: "137 minute",
		language: "English",
		rating: "6.8 Imdb",
		season: null,
		genre: "Documentary",
		certification: "UA",
	},
	{
		title: "The Shining",
		description:
			"A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
		year: "1980",
		director: "Stanley Kubrick",
		cast: "Jack Nicholson",
		runtime: "146 minutes",
		language: "English",
		rating: "8.4 Imdb",
		season: null,
		genre: "Drama,Horror",
		certification: "A",
	},
	{
		title: "The Boys",
		description:
			"THE BOYS is an irreverent take on what happens when superheroes, who are as popular as celebrities, as influential as politicians and as revered as Gods, abuse their superpowers rather than use them for good. It's the powerless against the super powerful as The Boys embark on a heroic quest to expose the truth about “The Seven,” and their formidable Vought backing.",
		year: "2019",
		director: "Eric Kripke",
		cast: "BILLY BUTCHER",
		runtime: "483 minutes",
		language: "English[CC]",
		rating: "8.7 Imdb",
		episodes: "8 episodes",
		season: "2 Seasons",
		genre: "Comedy, Action",
		certification: "A",
	},
	{
		title: "Gravity",
		description:
			"Two astronauts work together to survive after an accident leaves them stranded in space.",
		year: "2013",
		director: "Alfonso Cuarón",
		cast: "George Clooney",
		runtime: "91 minutes",
		language: "English",
		rating: "7.7 Imdb",
		season: null,
		genre: "Action,Drama,Sci-Fi",
		certification: "UA",
	},
	{
		title: "Knives Out",
		description:
			"A detective investigates the death of a patriarch of an eccentric, combative family.",
		year: "2019",
		director: "Rian Johnson",
		cast: "Daniel Craig",
		runtime: "130 minutes",
		language: "English",
		rating: "7.9 Imdb",
		season: null,
		genre: "Comedy,Crime,Drama",
		certification: "A",
	},
];
